//
// AUTO-GENERATED by build hook.  Do not edit or commit
//
#define AG_MRAIDWKWEBVIEW_BUILD_HASH    @"16d3a706b150a38aab2f7354adff6e99184e3cc8"
#define AG_MRAIDWKWEBVIEW_BUILD_TAG     @""
#define AG_MRAIDWKWEBVIEW_BUILD_DATE    @"Fri Nov 10 14:22:09 EST 2017"
