//
// AUTO-GENERATED by build hook.  Do not edit or commit
//
#define AG_MRAIDWKWEBVIEW_BUILD_HASH    @"10b00341f7139c9f1bccb6b549230fa02c7dfc7e"
#define AG_MRAIDWKWEBVIEW_BUILD_TAG     @""
#define AG_MRAIDWKWEBVIEW_BUILD_DATE    @"Mon Dec 17 14:09:44 EST 2018"
