//
// AUTO-GENERATED by build hook.  Do not edit or commit
//
#define AG_EVENTMANAGER_BUILD_HASH   @"e54e80e8002765e07e66dcb17abcf2bb8ae56cce"
#define AG_EVENTMANAGER_BUILD_TAG    @""
#define AG_EVENTMANAGER_BUILD_DATE   @"Fri Nov 10 15:23:34 EST 2017"
