//
// AUTO-GENERATED by build hook.  Do not edit or commit
//
#define AG_EVENTMANAGER_BUILD_HASH   @"575b9d932634c2ac85dc2900c3a1d31d7d481e8c"
#define AG_EVENTMANAGER_BUILD_TAG    @"5.2.0"
#define AG_EVENTMANAGER_BUILD_DATE   @"Mon Dec 17 12:27:18 EST 2018"
